services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:H2bkf5Kcl2kWM6SFVaTtebbl7c4PPG3xLWW22TIzToI=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://naadali.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d24e8kp5pdvs738910lg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: naadali_portfolio
      - key: DB_USERNAME
        value: naadali_portfolio_user
      - key: DB_PASSWORD
        value: Rethjgf9WK6h4PaEFwuNBxJOgx2q54DH
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: file
